### ISSUE TITLE
Potentially Incompatable with Among Us v.2021.3.5s

### ISSUE THREAD

**Issue by jsk663** [NotHunter101/ExtraRolesAmongUs#79] opened 2021-03-05 22:47 UTC
I followed the install directions for the latest version of the mod (Extra Roles v1.3.1). This included hitting the button to replace file duplicates when prompted by my file explorer. Additionally, the issue may be related to Among Us releasing an update today titled v.2021.3.5s. Below is what I am seeing in the command window. When I open Among us I am not seeing "Mods: 3" and "Extra Roles Mod vX.X.X Loaded." (X.X.X being the current version number)"

[Message: Preloader] BepInEx 6.0.0-reactor.16 - Among Us
[Message: Preloader] BLEEDING EDGE Build #16 from a44ed820546a57f00af344eb86ba879e270b71d3 at reactor
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2019.4.9.5308042
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 5 plugins to load
[Warning:   BepInEx] Skipping [Reactor 0.2.0] because a newer version exists (Reactor 0.3.0-ci.38)
[Info   :   BepInEx] Loading [Reactor 0.3.0-ci.38]
[Error  :   BepInEx] Error loading [Reactor 0.3.0-ci.38] : Exception has been thrown by the target of an invocation.
[Warning:   BepInEx] Skipping [Essentials 0.1.0] because it has a dependency that was not loaded. See previous errors for details.
[Warning:   BepInEx] Skipping [ExtraRoles 1.3.1] because it has a dependency that was not loaded. See previous errors for details.
[Warning:   BepInEx] Skipping [Jester 1.0.0] because it has a dependency that was not loaded. See previous errors for details.
[Message:   BepInEx] Chainloader startup complete
Setting breakpad minidump AppID = 945360
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197970543927 [API loaded no]

**Comment by ItsL3w1s** [comment] 2021-03-06 01:06
Dupe of #78 Reactor needs to update

**Comment by NotHunter101** [comment] 2021-03-06 19:57
Duplicate of #78. See above.

**Closed by NotHunter101** 2021-03-06 19:57 UTC
