### ISSUE TITLE
Mod is not loading in Among Us Version 2021.3.5s

### ISSUE THREAD

**Issue by c0d3knecht** [NotHunter101/ExtraRolesAmongUs#83] opened 2021-03-07 16:00 UTC
Updated Among Us early this morning, created an new folder with the Among Us Mod and copy the updated Among Us dir into this new folder.  
all seems to be fine, but in Among us, there are no extra roles any more.

It would be very nice, if this issue can be fixed, it makes more fun with these extras classes.

**Comment by Plusgaming1** [comment] 2021-03-07 16:43
Same problem for me

**Comment by RoadJDK** [comment] 2021-03-07 17:29
+1

**Comment by lambcount** [comment] 2021-03-07 18:21
+1

**Comment by NotHunter101** [comment] 2021-03-07 18:59
Duplicate of #78

**Comment by Senjyou-matsuri** [comment] 2021-03-08 02:42
Same problem +2

**Comment by timboOrhinoO** [comment] 2021-03-08 19:07
Yeah. New game version is producing lost dependencies on game load.

**Comment by Flex7z** [comment] 2021-03-08 19:46
Hey, could someone upload the among us files of an earlier version on which the mod still works?

**Comment by timboOrhinoO** [comment] 2021-03-08 20:01
@Flex7z :
is not working, since you cannot connect to the servers anymore with an older version.

**Comment by Flex7z** [comment] 2021-03-09 00:03
> 
> 
> @Flex7z :
> is not working, since you cannot connect to the servers anymore with an older version. guess the server is checking the game version.

But i saw streamer playing with mods, so how can they play?

**Comment by SsjSilentTV** [comment] 2021-03-09 09:49
> Updated Among Us early this morning, created an new folder with the Among Us Mod and copy the updated Among Us dir into this new folder.
> all seems to be fine, but in Among us, there are no extra roles any more.
> 
> It would be very nice, if this issue can be fixed, it makes more fun with these extras classes.

Hey all, 

So the mods still work as long as you don't use the updated among us files. Yes this means you'll be playing the mods on an older version however it still works and connects to the servers 

I've made another folder called "old version" as I wanted to get the towns mod working and it worked 

hope what i've said has helped anyone

**Comment by RedLightning42** [comment] 2021-03-09 14:57
> So the mods still work as long as you don't use the updated among us files. Yes this means you'll be playing the mods on an older version however it still works and connects to the servers

This is now false, as of yesterday the public servers are checking version numbers and won't allow the old version to connect. You need to use a private server or wait for Hunter to update the mod (or Slushie for Town of Us).

**Comment by NyphoX** [comment] 2021-03-09 20:25
The Reactor-issue (https://github.com/NuclearPowered/Reactor/issues/12) you've mentioned in the other issue concerning this problem (https://github.com/NotHunter101/ExtraRolesAmongUs/issues/78) has been closed and the repo updated a few hours ago. I.e. Reactor was updated.

**Comment by NotHunter101** [comment] 2021-03-10 13:42
The mod has been updated to the newest version.

**Closed by NotHunter101** 2021-03-10 13:42 UTC
