### ISSUE TITLE
ArgumentOutOfRangeException: Index was out of range.

### ISSUE THREAD

**Issue by Becold** [NotHunter101/ExtraRolesAmongUs#60] opened 2021-02-25 22:14 UTC
Hi

The imposters got a double kills and someone pressed the buzzer.
We kicked off the Joker and he won the game.

But in the console, there were an error, we all saw the "defeat" screen empty (without anyone) and we could not restart the game.

Stacktrace:
![image](https://user-images.githubusercontent.com/12863317/109225527-ad014d00-77bd-11eb-87f4-037daad136bf.png)

**Comment by NotHunter101** [comment] 2021-03-11 22:03
This is a known bug that will be fixed in a future update.

**Comment by NotHunter101** [comment] 2021-03-11 22:09
Also, this is a duplicate of #77, so I'm going to close it.

**Closed by NotHunter101** 2021-03-11 22:09 UTC
